### ISSUE TITLE
[Windows] TypeError: hex is not a function

### ISSUE THREAD

**Issue by coolaj86** [Daplie/rsa-compat.js#9]
As per https://github.com/Daplie/letsencrypt-cli/issues/16

```
TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at _bigIntToBase64Url (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:10:20)
    at Object.module.exports._forgeToPrivateJwk (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:41:10)
    at Object.module.exports.exportPrivateJwk (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:105:21)
    at C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\node.js:88:47
    at Object.module.exports.generateKeypair (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-ursa.js:44:5)
    at Object.RSA.generateKeypair (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\node.js:86:19)
    at Object.tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\util.js:16:23)
    at Object.ret [as generateKeypairAsync] (eval at <anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at Object.createAccount (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\lib\accounts.js:16:14)
    at C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\lib\core.js:405:25
```

**Comment by coolaj86** [comment]
@JohannesHoppe What version of node.js are you running?

```
node --version
```

I want to fix this with v4.x and below, but just for sanity make sure you try with v6.x

**Comment by coolaj86** [comment]
Also, put a `console.log('hex', hex)` just before this line and re-run and tell me if you get a string:

https://github.com/Daplie/rsa-compat.js/blob/master/lib/rsa-extra.js#L10

I just tested on v6 on OS X and it's working fine, so this is either a problem with v4 or with Windows.

**Comment by gardient** [comment]
output on windows 10 with the console log is

```
hex 818afc8cce82c96b750a64352940054af6a581dc50403ddc939d29bca104a8c3db21f6f58fcc6fbd3131f4ea8b795e0dcfc554f4340d847e652fa73fd00208df66ea0b6a4b6fca59970a6f27dc5365f127b34db603d8b37b84e8070983bdb846d2f2d288e33ebdbb7eba1c766ce3457f3ea72b31d9c01ec68de55989050177dc01ded42c7d9a03676704c51475d16c07e4bb4c3defe4b6b79545b265f44249d2d4fedf739f56e07588d59bc5ea7ddf53700a6b2100068ba4ab7060193289a5634e5fd42f74106e809e44c7bfc68e9eaba6fd94d828da64fe10ad138d31c6231eae0cc87cab397b2d7c59e377b4cd7132c13d91a5f3b6ac1df2e23aca2d309773
[Error]: letsencrypt-cli
TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at _bigIntToBase64Url (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:11:20)
    at Object.module.exports._forgeToPrivateJwk (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:42:10)
    at Object.module.exports.exportPrivateJwk (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:106:21)
    at C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\node.js:87:47
    at Object.module.exports.generateKeypair (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-forge.js:66:5)
    at Object.RSA.generateKeypair (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\node.js:85:19)
    at Object.tryCatcher (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\util.js:16:23)
    at Object.ret [as generateKeypairAsync] (eval at <anonymous> (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\lib\core.js:75:24
    at tryCatcher (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:630:18)
    at Promise._resolveCallback (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:425:57)
    at Promise._settlePromiseFromHandler (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:516:17)
    at Promise._settlePromise (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Gyuszi\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\le-store-certbot\node_modules\bluebird\js\release\promise.js:685:18)
```

sorry to barge in, just having the same problem

**Comment by JohannesHoppe** [comment]
I am right now on node v4.2.2 (windows). I could test the suggested steps in a couple of hours, when I'm home again.

**Comment by coolaj86** [comment]
@gardient what version of node?

**Comment by coolaj86** [comment]
Both:

try this in the node REPL and tell me what you get:

```
var hex = '818afc8cce82c96b750a64352940054af6a581dc50403ddc939d29bca104a8c3db21f6f58fcc6fbd3131f4ea8b795e0dcfc554f4340d847e652fa73fd00208df66ea0b6a4b6fca59970a6f27dc5365f127b34db603d8b37b84e8070983bdb846d2f2d288e33ebdbb7eba1c766ce3457f3ea72b31d9c01ec68de55989050177dc01ded42c7d9a03676704c51475d16c07e4bb4c3defe4b6b79545b265f44249d2d4fedf739f56e07588d59bc5ea7ddf53700a6b2100068ba4ab7060193289a5634e5fd42f74106e809e44c7bfc68e9eaba6fd94d828da64fe10ad138d31c6231eae0cc87cab397b2d7c59e377b4cd7132c13d91a5f3b6ac1df2e23aca2d309773';

new Buffer(hex, 'hex');

new Buffer.from(hex, 'hex');
```

I wonder if `Buffer.from` exists experimentally in node v4.x and is broken or something. That would be annoying to figure out, but perhaps I could put a `try { } catch (e) {}` around `Buffer.from()`

**Comment by gardient** [comment]
@coolaj86 output is:
```
> var hex = '818afc8cce82c96b750a64352940054af6a581dc50403ddc939d29bca104a8c3db21f6f58fcc6fbd3131f4ea8b795e0dcfc554f4340d847e652fa73fd00208df66ea0b6a4b6fca59970a6f27dc5365f127b34db603d8b37b84e8070983bdb846d2f2d288e33ebdbb7eba1c766ce3457f3ea72b31d9c01ec68de55989050177dc01ded42c7d9a03676704c51475d16c07e4bb4c3defe4b6b79545b265f44249d2d4fedf739f56e07588d59bc5ea7ddf53700a6b2100068ba4ab7060193289a5634e5fd42f74106e809e44c7bfc68e9eaba6fd94d828da64fe10ad138d31c6231eae0cc87cab397b2d7c59e377b4cd7132c13d91a5f3b6ac1df2e23aca2d309773';
undefined
> new Buffer(hex, 'hex');
<Buffer 81 8a fc 8c ce 82 c9 6b 75 0a 64 35 29 40 05 4a f6 a5 81 dc 50 40 3d dc 93 9d 29 bc a1 04 a8 c3 db 21 f6 f5 8f cc 6f bd 31 31 f4 ea 8b 79 5e 0d cf c5 ... >
> new Buffer.from(hex, 'hex');
TypeError: function from() { [native code] } is not a constructor
    at repl:1:1
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
> Buffer.from(hex, 'hex');
TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
```

also versions as per REPL:
```
> process.versions
{ http_parser: '2.5.2',
  node: '4.4.7',
  v8: '4.5.103.36',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2h' }
```

**Comment by JohannesHoppe** [comment]
ok, this is something i can do right now.
result for node v4.2.2 on windows


```                                                                                                                                     
node                                                                                                                                                
> var hex = '818afc8cce82c96b750a64352940054af6a581dc50403ddc939d29bca104a8c3db21f6f58fcc6fbd3131f4ea8b795e0dcfc554f4340d847e652fa73fd00208df66ea0b6a4
b6fca59970a6f27dc5365f127b34db603d8b37b84e8070983bdb846d2f2d288e33ebdbb7eba1c766ce3457f3ea72b31d9c01ec68de55989050177dc01ded42c7d9a03676704c51475d16c0
7e4bb4c3defe4b6b79545b265f44249d2d4fedf739f56e07588d59bc5ea7ddf53700a6b2100068ba4ab7060193289a5634e5fd42f74106e809e44c7bfc68e9eaba6fd94d828da64fe10ad1
38d31c6231eae0cc87cab397b2d7c59e377b4cd7132c13d91a5f3b6ac1df2e23aca2d309773';                                                                         
> var hex = '818afc8cce82c96b750a64352940054af6a581dc50403ddc939d29bca104a8c3db21f6f58fcc6fbd3131f4ea8b795e0dcfc554f4340d847e652fa73fd00208df66ea0b6a4
b6fca59970a6f27dc5365f127b34db603d8b37b84e8070983bdb846d2f2d288e33ebdbb7eba1c766ce3457f3ea72b31d9c01ec68de55989050177dc01ded42c7d9a03676704c51475d16c0
7e4bb4c3defe4b6b79545b265f44249d2d4fedf739f56e07588d59bc5ea7ddf53700a6b2100068ba4ab7060193289a5634e5fd42f74106e809e44c7bfc68e9eaba6fd94d828da64fe10ad1
38d31c6231eae0cc87cab397b2d7c59e377b4cd7132c13d91a5f3b6ac1df2e23aca2d309773';                                                                         
undefined                                                                                                                                             
>                                                                                                                                                     
> new Buffer(hex, 'hex');                                                                                                                             
<Buffer 81 8a fc 8c ce 82 c9 6b 75 0a 64 35 29 40 05 4a f6 a5 81 dc 50 40 3d dc 93 9d 29 bc a1 04 a8 c3 db 21 f6 f5 8f cc 6f bd 31 31 f4 ea 8b 79 5e 0
d cf c5 ... >                                                                                                                                         
>                                                                                                                                                     
> new Buffer.from(hex, 'hex');                                                                                                                        
TypeError: function from() { [native code] } is not a constructor                                                                                     
    at repl:1:1                                                                                                                                       
    at REPLServer.defaultEval (repl.js:248:27)                                                                                                        
    at bound (domain.js:280:14)                                                                                                                       
    at REPLServer.runBound [as eval] (domain.js:293:12)                                                                                               
    at REPLServer.<anonymous> (repl.js:412:12)                                                                                                        
    at emitOne (events.js:82:20)                                                                                                                      
    at REPLServer.emit (events.js:169:7)                                                                                                              
    at REPLServer.Interface._onLine (readline.js:210:10)                                                                                              
    at REPLServer.Interface._line (readline.js:549:8)                                                                                                 
    at REPLServer.Interface._ttyWrite (readline.js:826:14)                                                                                            
>                                                                                                                                                     
```

**Comment by coolaj86** [comment]
oops, I meant `Buffer.from(hex, 'hex');`, not `new Buffer.from(hex, 'hex');`

However, from what I see it looks like a broken version of `Buffer.from` is included in v4.x.

Man... polyfills suck sometimes.

Try with v6.x and I bet that will work. I'll also throw a `try {} catch () {}` in there...

**Comment by coolaj86** [comment]
Published rsa-compat v1.26 with the fix. `rm -rf node_modules; npm install` and try again

**Comment by coolaj86** [comment]
Reported the bug to node proper https://github.com/nodejs/node/issues/8053

**Comment by coolaj86** [comment]
Con you confirm that the latest version works for you?

**Comment by coolaj86** [comment]
The node team says they're backporting Buffer.from to v4.5.

**Comment by gardient** [comment]
@coolaj86 yes I can confirm that the latest version is working. Thanks for the quick fix
